### ISSUE TITLE
Error while compiling gcc

### ISSUE THREAD

**Issue by mdodballapur** [Tatsh/xchain#5]
Hi,

I have been unable to compile 64 bit version of x86_64-apple-darwin-gcc cross compiler and it fails with the following error 

/gcc/xgcc -B/home/xxxxx/build-gcc-5566.3_try2/./gcc/ -B/opt/x86_64-apple-darwin10/usr/bin/ -B/opt/x86_64-apple-darwin10/usr/lib/ -isystem /opt/x86_64-apple-darwin10/usr/include -isystem /opt/x86_64-apple-darwin10/usr/sys-include  -mmacosx-version-min=10.4 -O2  -O2 -DIN_GCC -DCROSS_DIRECTORY_STRUCTURE   -W -Wall -Wwrite-strings -Wstrict-prototypes -Wmissing-prototypes -Wold-style-definition  -isystem ./include  -fPIC -pipe -g -DHAVE_GTHR_DEFAULT -DIN_LIBGCC2 -D__GCC_FLOAT_NOT_NEEDED  -I. -I. -I../../gcc-5666.3/gcc -I../../gcc-5666.3/gcc/. -I../../gcc-5666.3/gcc/../include -I../../gcc-5666.3/gcc/../libcpp/include -Ino/include -Ino/include -I../../gcc-5666.3/gcc/../libdecnumber -I../libdecnumber -DL_muldi3  -c ../../gcc-5666.3/gcc/libgcc2.c -o libgcc/./_muldi3.o
1:37:Rest of line ignored. 1st junk character valued 34 (").
1:38:Unknown pseudo-op: .loc
1:38:Rest of line ignored. 1st junk character valued 49 (1).
1:44:Unknown pseudo-op: .loc
1:44:Rest of line ignored. 1st junk character valued 49 (1).
1:49:Unknown pseudo-op: .loc
1:49:Rest of line ignored. 1st junk character valued 49 (1).
1:55:Unknown pseudo-op: .loc
1:55:Rest of line ignored. 1st junk character valued 49 (1).
1:107:Unknown pseudo-op: .loc
1:107:Rest of line ignored. 1st junk character valued 49 (1).
1:114:Unknown pseudo-op: .loc
1:114:Rest of line ignored. 1st junk character valued 49 (1).
2:307:Rest of line ignored. 1st junk character valued 34 (").
make[3]: **\* [libgcc/./_muldi3.o] Error 1

It seems like the assembler is failing. Any ideas ?

**Comment by Tatsh** [comment]
If I choose to update this project, it's switching to 100% Clang to match up to the current SDK.
